-- ===================================================================================
-- SCRIPT DE EXECUÇÃO DO ETL
-- Descrição: Use este script para carregar e processar os dados.
--            Você pode executá-lo sempre que quiser.
-- ===================================================================================
USE mortalidade;
GO

PRINT '--- INÍCIO DO PROCESSO DE ETL ---';

-- ===================================================================================
--  ** ATENÇÃO: VERIFIQUE OS CAMINHOS DOS FICHEIROS ANTES DE EXECUTAR! **
-- ===================================================================================

DECLARE @CaminhoObitos NVARCHAR(MAX) = '/var/opt/mssql/data/DO24OPEN_clean.csv';
-- ===================================================================================

-- Etapa 1: Preparar e executar o ETL dos óbitos
PRINT 'Etapa 2: Iniciando ETL de óbitos...';
CREATE TABLE #stg_dados_brutos (
    -- Definição completa das 89 colunas aqui...
    contador VARCHAR(10), ORIGEM VARCHAR(10), TIPOBITO VARCHAR(1), DTOBITO VARCHAR(8), HORAOBITO VARCHAR(5), NATURAL VARCHAR(3), CODMUNNATU VARCHAR(7), DTNASC VARCHAR(8), IDADE VARCHAR(3), SEXO VARCHAR(1), RACACOR VARCHAR(1), ESTCIV VARCHAR(1), ESC VARCHAR(1), ESC2010 VARCHAR(1), SERIESCFAL VARCHAR(1), OCUP VARCHAR(6), CODMUNRES VARCHAR(7), LOCOCOR VARCHAR(1), CODESTAB VARCHAR(8), CODMUNOCOR VARCHAR(8), IDADEMAE VARCHAR(2), ESCMAE VARCHAR(1), ESCMAE2010 VARCHAR(1), SERIESCMAE VARCHAR(1), OCUPMAE VARCHAR(6), QTDFILVIVO VARCHAR(2), QTDFILMORT VARCHAR(2), GRAVIDEZ VARCHAR(1), SEMAGESTAC VARCHAR(3), GESTACAO VARCHAR(1), PARTO VARCHAR(1), OBITOPARTO VARCHAR(1), PESO VARCHAR(4), TPMORTEOCO VARCHAR(1), OBITOGRAV VARCHAR(1), OBITOPUERP VARCHAR(1), ASSISTMED VARCHAR(1), EXAME VARCHAR(1), CIRURGIA VARCHAR(1), NECROPSIA VARCHAR(1), LINHAA VARCHAR(20), LINHAB VARCHAR(20), LINHAC VARCHAR(20), LINHAD VARCHAR(20), LINHAII VARCHAR(45), CAUSABAS VARCHAR(4), CB_PRE VARCHAR(10), COMUNSVOIM VARCHAR(7), DTATESTADO VARCHAR(8), CIRCOBITO VARCHAR(1), ACIDTRAB VARCHAR(1), FONTE VARCHAR(1), NUMEROLOTE VARCHAR(8), DTINVESTIG VARCHAR(8), DTCADASTRO VARCHAR(8), ATESTANTE VARCHAR(1), STCODIFICA VARCHAR(1), CODIFICADO VARCHAR(1), VERSAOSIST VARCHAR(7), VERSAOSCB VARCHAR(7), FONTEINV VARCHAR(8), DTRECEBIM VARCHAR(8), ATESTADO VARCHAR(70), DTRECORIGA VARCHAR(8), OPOR_DO VARCHAR(4), CAUSAMAT VARCHAR(4), ESCMAEAGR1 VARCHAR(2), ESCFALAGR1 VARCHAR(2), STDOEPIDEM VARCHAR(1), STDONOVA VARCHAR(1), DIFDATA VARCHAR(8), NUDIASOBCO VARCHAR(4), DTCADINV VARCHAR(8), TPOBITOCOR VARCHAR(1), DTCONINV VARCHAR(8), FONTES VARCHAR(6), TPRESGINFO VARCHAR(2), TPNIVELINV VARCHAR(1), DTCADINF VARCHAR(8), MORTEPARTO VARCHAR(1), DTCONCASO VARCHAR(8), ALTCAUSA VARCHAR(1), CAUSABAS_O VARCHAR(4), TPPOS VARCHAR(1), TP_ALTERA VARCHAR(2), CB_ALT VARCHAR(10)
);

EXEC sp_Extract_Obitos_from_CSV @CaminhoArquivoCSV = @CaminhoObitos;
EXEC sp_Transform_and_Load_Obitos;

DROP TABLE #stg_dados_brutos;
PRINT 'ETL de óbitos concluído.';

-- Etapa 2: Verificação Final
PRINT '--- Verificação Final de Dados ---';
SELECT 'municipio' AS Tabela, COUNT(*) AS TotalRegistros FROM municipio
UNION ALL
SELECT 'obito' AS Tabela, COUNT(*) AS TotalRegistros FROM obito;
GO

PRINT '======== PROCESSO DE ETL CONCLUÍDO! ========';
GO


