USE mortalidade;
GO

IF OBJECT_ID('sp_extract_cnes', 'P') IS NOT NULL
    DROP PROCEDURE sp_extract_cnes;
GO

CREATE PROCEDURE sp_extract_cnes
    @caminho VARCHAR(500)
AS
BEGIN
    CREATE TABLE ##temp_cnes (
        CO_CNES VARCHAR(MAX),
        CO_UNIDADE VARCHAR(MAX),
        CO_UF VARCHAR(MAX),
        CO_IBGE VARCHAR(MAX),
        NU_CNPJ_MANTENEDORA VARCHAR(MAX),
        NO_RAZAO_SOCIAL VARCHAR(MAX),
        NO_FANTASIA VARCHAR(MAX),
        CO_NATUREZA_ORGANIZACAO VARCHAR(MAX),
        DS_NATUREZA_ORGANIZACAO VARCHAR(MAX),
        TP_GESTAO VARCHAR(MAX),
        CO_NIVEL_HIERARQUIA VARCHAR(MAX),
        DS_NIVEL_HIERARQUIA VARCHAR(MAX),
        CO_ESFERA_ADMINISTRATIVA VARCHAR(MAX),
        DS_ESFERA_ADMINISTRATIVA VARCHAR(MAX),
        CO_ATIVIDADE VARCHAR(MAX),
        TP_UNIDADE VARCHAR(MAX),
        CO_CEP VARCHAR(MAX),
        NO_LOGRADOURO VARCHAR(MAX),
        NU_ENDERECO VARCHAR(MAX),
        NO_BAIRRO VARCHAR(MAX),
        NU_TELEFONE VARCHAR(MAX),
        NU_LATITUDE VARCHAR(MAX),
        NU_LONGITUDE VARCHAR(MAX),
        CO_TURNO_ATENDIMENTO VARCHAR(MAX),
        DS_TURNO_ATENDIMENTO VARCHAR(MAX),
        NU_CNPJ VARCHAR(MAX),
        NO_EMAIL VARCHAR(MAX),
        CO_NATUREZA_JUR VARCHAR(MAX),
        ST_CENTRO_CIRURGICO VARCHAR(MAX),
        ST_CENTRO_OBSTETRICO VARCHAR(MAX),
        ST_CENTRO_NEONATAL VARCHAR(MAX),
        ST_ATEND_HOSPITALAR VARCHAR(MAX),
        ST_SERVICO_APOIO VARCHAR(MAX),
        ST_ATEND_AMBULATORIAL VARCHAR(MAX),
        CO_MOTIVO_DESAB VARCHAR(MAX),
        CO_AMBULATORIAL_SUS VARCHAR(MAX)
    );

    DECLARE @Sql NVARCHAR(MAX);
    SET @Sql = N'
    BULK INSERT ##temp_cnes
    FROM ''' + @caminho + N'''
    WITH (
        FIRSTROW = 2,
        FIELDTERMINATOR = '';'',
        ROWTERMINATOR = ''\n'',
        CODEPAGE = ''1252''
    );';

    EXEC sp_executesql @sql;
END;
GO

IF OBJECT_ID('sp_transform_cnes', 'P') IS NOT NULL
    DROP PROCEDURE sp_transform_cnes;
GO

CREATE PROCEDURE sp_transform_cnes
AS
BEGIN
    ALTER TABLE ##temp_cnes
    DROP COLUMN CO_UNIDADE,CO_UF,CO_IBGE,NU_CNPJ_MANTENEDORA,CO_NATUREZA_ORGANIZACAO,DS_NATUREZA_ORGANIZACAO,TP_GESTAO,CO_NIVEL_HIERARQUIA,
    DS_NIVEL_HIERARQUIA,CO_ESFERA_ADMINISTRATIVA,DS_ESFERA_ADMINISTRATIVA,CO_ATIVIDADE,TP_UNIDADE,CO_CEP,NO_LOGRADOURO,NU_ENDERECO,
    NO_BAIRRO,NU_TELEFONE,NU_LATITUDE,NU_LONGITUDE,CO_TURNO_ATENDIMENTO,DS_TURNO_ATENDIMENTO,NU_CNPJ,NO_EMAIL,CO_NATUREZA_JUR,
    ST_CENTRO_CIRURGICO,ST_CENTRO_OBSTETRICO,ST_CENTRO_NEONATAL,ST_ATEND_HOSPITALAR,ST_SERVICO_APOIO,ST_ATEND_AMBULATORIAL,CO_MOTIVO_DESAB,CO_AMBULATORIAL_SUS;

    IF OBJECT_ID('tempdb..##temp_cnes_trans') IS NOT NULL
        DROP TABLE ##temp_cnes_trans;

    CREATE TABLE ##temp_cnes_trans (
            CO_CNES CHAR(8), 
            NO_RAZAO_SOCIAL VARCHAR(256),
            NO_FANTASIA VARCHAR(256)
        );

    INSERT INTO ##temp_cnes_trans (CO_CNES, NO_RAZAO_SOCIAL, NO_FANTASIA)
    SELECT 
        CAST(REPLACE(CO_CNES, '"', '') AS CHAR(8)),
        CAST(REPLACE(NO_RAZAO_SOCIAL, '"', '') AS VARCHAR(256)),
        CAST(REPLACE(NO_FANTASIA, '"', '') AS VARCHAR(256))
    FROM ##temp_cnes;

    DROP TABLE ##temp_cnes;
END;
GO

IF OBJECT_ID('sp_load_cnes', 'P') IS NOT NULL
    DROP PROCEDURE sp_load_cnes;
GO

CREATE PROCEDURE sp_load_cnes
AS
BEGIN
    INSERT INTO cnes_estabelecimento (codigo_cnes, nome_razaosocial, nome_fantasia)
    SELECT
        temp.CO_CNES,
        temp.NO_RAZAO_SOCIAL,
        temp.NO_FANTASIA
    FROM ##temp_cnes_trans AS temp
    WHERE NOT EXISTS (
        SELECT 1 
        FROM cnes_estabelecimento AS c 
        WHERE c.codigo_cnes = temp.CO_CNES
    );
END;
GO

IF OBJECT_ID('sp_ETL_cnes', 'P') IS NOT NULL
    DROP PROCEDURE sp_ETL_cnes;
GO

CREATE PROCEDURE sp_ETL_cnes
    @caminhoArquivo VARCHAR(500)
AS
BEGIN
    EXEC sp_extract_cnes @caminho = @caminhoArquivo;
    EXEC sp_transform_cnes;
    EXEC sp_load_cnes;
    DROP TABLE ##temp_cnes_trans;
END;
GO
